apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:3ei9+SVjGn5SW+Yqmbpn0HcXVrTtYLiMhUyoly5lIZ5H2AI2ec0X80h1kKBZhzlOZM6WALrtXQQPCwhMII/sH9dKhdcgXoWX3IrHe3gl4oIEQ0OCrEb3j0dEDlm2Z8ACngQ7VgNBLMm1HHndfCviJXQ+mdXPbFOljf8KhLFAdxzYqzTS3YpPvmldvv37qYfckE9BCU+dsXAOJJUL40pcYXDgI+YnrzEU+0Z22vcGj82ekFhLD/Z3AFbaMmVhrlSuU7Dao5zhQhzv1rF1xvYFVg/H7SMwIho8dQTCas4+5yo4a4i7qElJUL1R2gOVucBDFTIEb+S5z4C6vhSw862Tb+Owp1YbpzCbCiSqRhiCWaBBTwl73MmqFudO2W8O0l4nN5eYZGtR3IgEHxfxJkL+BSQjPszVrdwXy6/WdLMYWxkKGNrnsCdAAEjjKdah5nFW2W8A+NCoY38Akvc3K4exNgyUJ39Y1NOSYP6NFA==,iv:+lpQLTJYuppMcPmMpiOKVkwR9YsU+c0xaWVMT4vhehg=,tag:QAbpETcMicLAzNLQzF834g==,type:str]
kind: Secret
metadata:
    name: cloudflared-config
    namespace: rolechat
type: Opaque
sops:
    age:
        - recipient: age10jftd4a6z00h37trzsvrst5nsqu477tx67yfxqdhf07gj233tu3q6peps3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRTlyNjg1YVBZSW5OWDFu
            cWtjQ1VvL3Q2Tm95d1RITjdxcUIyei80QUVjCkRRTFhuTUFsWFJBVHU0M21FRkRZ
            QUM5eEdOMzhiZFdnTmhwOHNLbytxYkUKLS0tIDZOeExRZmZLRk5WSk43SSsySUg3
            STVHSlk2c044VjJSelgwSGhsdzhrWmcK5imLhloR7jf/r4qhdnSsOpsxPrYHW2Bq
            V2HZdeA95zYyJ4cpH17En4NcBfwMHMh4iIOcPxYCgtN3OJT9J+/8vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-08T04:02:01Z"
    mac: ENC[AES256_GCM,data:Jh9pRGXWpN7quGZiI3+hG2p3Iw2lYauKJh8TuiKRkMp/trGjI63KwyNgYfI6JkUGancZICCxxVRf6Tr07NIQ0MJ9sPBLfcO6bx10bJ+jNcSC+1KG2O76fkHwuF6NtSbxuBcaFO1tg1aPOfe6QME/toOCp9tj7b7FAPniply9Mtk=,iv:1pfaOBGoikaqCWt6DmwxCJs0+nQukXWBNNBGPBFAmbo=,tag:un2eed//2Kpjns7ZmtwBHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
