apiVersion: v1
data:
    9bd01f73-78af-4b55-a16f-ae3e490b83a4.json: ENC[AES256_GCM,data:gZRNG+5zZ89V8ClfqNFymju40LAhR7MJvtrExUwDAoQZp6uP9E8lo67Ect4SIio5r9kAeUDPrDB4dZaIiKjF1HslfYLZPxRPC9jq5boDPYU1VpZd9VT/mBzXgi2QyLpXHCRq9698ztAH3huMfrXJFsiIHIF2CbLor8GTXgD+rnQ2bk+uvtVtgdPqeNC4gxKY9Df+xsr8w2Lbmtcb00WKcQBE2gfUI5eXhcJeC7Fd2huKHdSyy42g0mjtXZsE5FPjs6OUGzSnETQMi3a4h4RE2k0QGIUEuAcdRYpeDOgUlpbTv1KjNZCllBs7HOA=,iv:IR61WVxSG8hQJzVk+0pbeUJHHF/Bus8b4rJKdbOsUSw=,tag:0RpURAxiP3v1lu0GkEbBmQ==,type:str]
kind: Secret
metadata:
    name: cloudflared-creds
    namespace: rolechat
type: Opaque
sops:
    age:
        - recipient: age10jftd4a6z00h37trzsvrst5nsqu477tx67yfxqdhf07gj233tu3q6peps3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZkN0WjZ5UFZKbG1TZjZ2
            cFF6TWpNVVA2VVQvMlR6K2pBRnpLUjZFT2hjCktMS1dzWUxQYys3NDVxZkFRY1lJ
            dXdaWmFUYmdVd21UeEdUcjJldFFUbzgKLS0tIG1DZFN3YTFoZ09NRTBQZVBiSHdR
            QVRmaDkxYkRWamdYOEUxUFl0U3QzTzAK3bd9NKG/SszB8AnxN61j7Q4qaf4BuL22
            I4oxB/KPeQXKoijja27gU7DiGJtHmMydfj7YdDClNTHR9P7JGvw4sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-08T04:02:01Z"
    mac: ENC[AES256_GCM,data:wdqqXrLc38hrTzyg9Ea3IyBi+MXlcM37WVBqh7luK18ahckYJ15qCEo0zZsUmzN1lbs+Uj2CGW8ZWVNUask3lTbX1y75CvyHKOErBf881EAUzYfxTRwMNUtTYy04kXWPZ+kbwsW+fQ5vBNhSzKWKpvrzg+1pgfFmtXCecZJnRuI=,iv:sywxXa3YUEcLAI/c8gEgYBI3kX+XaJ2JKhX9KOHIrG0=,tag:Znixej+QNFxQpqibL1wipw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
