apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: rolechat-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./users-secret.enc.yaml
  - ./google-api-secret.enc.yaml
  - ./cloudflared-creds.enc.yaml
  - ./cloudflared-config.enc.yaml