apiVersion: v1
kind: Secret
metadata:
    name: google-api
    namespace: rolechat
type: Opaque
stringData:
    GOOGLE_API_KEY: ENC[AES256_GCM,data:ZearSuWQX/tfYw7L0izLdTtsNnfB+V7wT5bc8hWlw49mxyEuzXIN37iz/RGf3LdaevcIQ2c=,iv:l4wANvmcrp1S1sWl8BYNgpmoAvYXIT9r82siTTzeEpc=,tag:FQLVcAduiuXEhqUPHQS5dg==,type:str]
sops:
    age:
        - recipient: age10jftd4a6z00h37trzsvrst5nsqu477tx67yfxqdhf07gj233tu3q6peps3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQkxsZWZuOG41eWgwVlFa
            aUc5bmhFNitzcVRsTDNVdlNKUUZQK29kQ1djCjVzZDJiSHRWb3JGUE9ZWEdsbmQ1
            dVVFM0c0YVR4bEhyYW54Y0lhcVcxRTQKLS0tIDJsMXVWTkZocXRBL3IwbWVSYzJp
            c091MGJMcy8rNWZ4aWoxekVNa0JtMUEK27yrZkfNxMt4wcqEIUEGeFHgWS2gDSQu
            iEMPtPjSXGsiQ978W1A/G9GYwVMfyfzswMtk2yaT7b075xyOM0UFrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T23:05:41Z"
    mac: ENC[AES256_GCM,data:F4l1PAjha581JTV1/VeRmd5GCbof36DZaMKINBn8Ec1YekM/XVWEDX9/4VJ5SxU0lako9EzvBxGtIEW8fcnq9mIO/1qdPO7+Q59CVRYVBDuTp651EYq6YPn9Y4X6jVXqrk8LFUudkDpXV3zM4hUvkkK8VFlRBIRFMAvjKUT2dNM=,iv:oXhv8E0pwVruxx9Ui1ax3SCWqi2SnsK/r3S6nBOpuHw=,tag:hB/my1Jkjy6It0wJULdrBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
