apiVersion: v1
kind: Secret
metadata:
    name: google-api
    namespace: rolechat
type: Opaque
stringData:
    GOOGLE_API_KEY: ENC[AES256_GCM,data:rQKrI1Cco6jhJ00+NBl2wn3vnbgP2u9yipVqAxJnnea7XDskmz2qvHQVG9NyKPnFeraFKM8=,iv:Mi3pawP+d4y+EmwXUfoPkZG5Il37SfjuY5gXnwtaVMc=,tag:QCvsym6zQcL/dd93xLx8kg==,type:str]
sops:
    age:
        - recipient: age10jftd4a6z00h37trzsvrst5nsqu477tx67yfxqdhf07gj233tu3q6peps3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYzFVYUJNQ1p3SkdCKzh1
            akhWUmpNNzV0SzhNVW1YYVh0SkpzcWZRVUVjCjRGeE1FVFRaUFhJREtMbXdEUDk2
            TEY3azd6UitJQ0ozOTJaUlRFUldCY1kKLS0tIGRsVjVyMHJnY2RKSUYzNVhhRlVQ
            UmpaRUtkQjVUdGpYZ2Z5aXpMVXJyaVkKXfPASv0w0vhFVwnaKmeOAPl0P9Nshrzw
            CRHw+hXnb/yo2sRcMEjxo5MMVZjPf+OhAUZJqOgUlK/f2UoZOV4Vwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T22:45:44Z"
    mac: ENC[AES256_GCM,data:Ip4+og/KQtkOKzgeXNBAaY0kLquPq9tPYxLiegpY2f/bc3FRElj7yDOaEhsA//RZ7XGyh1edE9+MaD3rSZld+vVRfZEk4h7k4tLO15Wtl/LhQhXjCglUedFkmyNzVEHuti0VS8qu54afezzBNuhrtv9EHH9E5HmJAylMzyLMaBc=,iv:BbhHkqbx78ZOQ9LRBAcP9YzNKG9BP03Y4eciFuOSOH8=,tag:EN9/VnAZuelkJmYLoFlDbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
