apiVersion: v1
kind: Secret
metadata:
    name: chatbot-users
    namespace: rolechat
type: Opaque
stringData:
    users.json: ENC[AES256_GCM,data:COeUG6kewBunHHT5Quh0PYT16gnPkgtFDQgKr48wF8BfRDJjqVWiVLtGAb5EO1Nv/FAhH2aid4BdJX3YPOIgHVuDT6So9ADVyiaK5o4WtJK5JYVaNLtLa/91vHjhRosFEkT5GFfojDWF1N+hpR8w3X/4PGuXkvPXgKngAyuF90vEYncMEp81iS6kKm9tfYKnxpcoQQyO2XVyvz0MJcswcdOT6axluacuqBF1maEcYnPDpZ20+nAQvS4qCqYcLfZ46xXAdsHlfHcqKFmCnPIE8TQrIRjc6CcLg7iBd1Z4jh4Z+dlB6H7KbljZDl+JfR9Lqsmhw3t48Ni8dSsmjHEJs4yOY1pSYnXhmLa/BaCIyG9lz1qVXM8l7H09zFL6pfktCaYKBLN5p85uPUM4+VtiWu/5CKf5Frs44AT6xPAHBZfXpDNTZ/DFIrXQ/dLXylZgeyqDyC3MNVICuR6Zd+6/jEBdF5QTkjBbRbDNr/1WvJ0mCJiqNqpIHCRNE5b6MzW+3RaGQhI8bAF0pvSbe+hurviKVxN8ridqbiGErifOrmC0utxKjUyXoMAgfQ5v7myCus0YQKRxwwLSZlkSz3fI0uEB2ZPAxWI6/mjtZ9gyDIMonFq+IHn6BigEbM97Ai9qsHTGztYaMc5Z/hNvRiiV8SlQL074DogC8muIBKlVbt300H2daud0HEHKkeQlgixd1Vv4JOjiRxeVzcTcACNTvWM3mnxZ3Psi51i0Da0MgjM0glJUQyJ49dwkIWsBUvh4PktO6M08xXAK6jKgp8OYtOX9R1EiIHZLvOoa5zeNDHg1WfERaWPJ1xuh8sC313aaEYZtrmCYZpMatDOShlz3gyv8uEscPPIAvMZ8KJ3TZ0ed4aPC9wa/807vqHOgh9NCI5hADETkUXnSVmcOGBfqUrc6QV6cHVtoOl46K8zy,iv:LbplKM8L+G3364mLjPDgEWXkM7aYDvTxAZRZ9xMxy7U=,tag:3+GLgXcNmjtv26G6Eunx8Q==,type:str]
sops:
    age:
        - recipient: age10jftd4a6z00h37trzsvrst5nsqu477tx67yfxqdhf07gj233tu3q6peps3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINHl6M1k0YW1VZFF5T2hO
            SU1nM0dTSHhSYTFWV2RGN21iUVFFSFJUeEM0CjQ2WXErWERKbyswaFlvc1VYUkpL
            dUtZZHVSdVRUL0FuU3BPNFBxTjhEMzAKLS0tIGUybWp1WDlLcWFvSzJ0K2hZcmNr
            T0ZxWlN2dkhjRUJNck9YaHlIWnVuM2sKwXtfhlrdgEr9C0FtaSnMsgvh7nzBoK5Q
            A8iho9P+dYOUSJpOBgCwGxwqrJF/VkdTXDfQH7o/XKfsK0dda7YH7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T21:50:46Z"
    mac: ENC[AES256_GCM,data:HevS2xOyG2MjIZJ70N4NJvh8nQSiBYC9gq3Rhh2hw3PKTZp2VMMj1FQJ5N13sqdO7M3k97x5hNn95oo8hpx/k6cqFiDk7U8Sh3xUexVKk0VnQLFYB5iUa684S3IaEvdI37NaDHEIM0tVUm5z4a6/pT/o2Ezbm9CnZXwVANI7lu8=,iv:QB1S1uxetiDcRasheA+UIB4HlCVfnfI5F7cEkQxjZy0=,tag:xAK7fuCNlek1Ze4RSlxxhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
