configs:
  cm:
    kustomize.buildOptions: --enable-alpha-plugins --enable-exec

repoServer:
  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.3.3
      command: ["/bin/sh", "-c"]
      args:
        - |
          set -e
          echo "Installing KSOPS..."
          cp "$(find / -name ksops -type f -perm -u+x 2>/dev/null | head -1)" /custom-tools/ksops
          chmod +x /custom-tools/ksops
          ls -l /custom-tools
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: sops-age
      secret:
        secretName: sops-age
  volumeMounts:
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
    - mountPath: /home/argocd/.config/sops/age
      name: sops-age
  env:
    - name: SOPS_AGE_KEY_FILE
      value: /home/argocd/.config/sops/age/keys.txt