apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-deploy.yaml
- chroma-pvc.yaml
- cloudflared-deploy.yaml
images:
- name: gowthamchowdam94/role-chatbot-api
  newName: gowthamchowdam94/role-chatbot-api
  newTag: 8e9f95e334db2a3289e23ee934030cb915d6ac96
