apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-deploy.yaml
- chroma-pvc.yaml
- cloudflared-deploy.yaml
images:
- name: gowthamchowdam94/role-chatbot-api
  newName: gowthamchowdam94/role-chatbot-api
  newTag: bc8e9de82138e3324d8c7ab4ef28b264625f9330
